# docker-compose.yml
version: "3"
services:
  app:
    env_file: .env
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
      - "9229:9229"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root@heed
